export const truths = () => {


    const tasks = [
        "What was the last thing you searched for on your phone?",
        "Have you ever walked in on your parents doing it?",
        "After you've dropped a piece of food, what's the longest time you've left it on the ground and then ate it?",
        "What's the first thing you would do if you woke up one day as the opposite sex?",
        "Have you ever peed in the pool?",
        "Who do you think is the worst dressed person in this game?",
        "Of the people in this room, who do you want to trade lives with?",
        "What are some things you think about when sitting on the toilet?",
        "Did your parents ever give you the “birds and the bees” talk?",
        "What is your guilty pleasure?",
        "What is your worst habit?",
        "Has anyone ever walked in on you when going #2 in the bathroom?",
        "Have you ever had a wardrobe malfunction?",
        "Do you sing in the shower?",
        "Have you ever peed yourself?",
        "What was your most embarrassing moment in public?",
        "Do you ever talk to yourself in the mirror?",
        "You’re in a public restroom and just went #2, then you realized your stall has no toilet paper. What do you do?",
        "What would be in your web history that you’d be embarrassed if someone saw?",
        "Have you ever tried to take a sexy picture of yourself?",
        "Who is the sexiest person in this game?",
        "Would you rather have sex with Päivi Räsänen in secret or not have sex with that person, but everyone thinks you did?",
        "What was the last thing you texted?",
        "If you were rescuing people from a burning building and you had to leave one person behind from this room, who would it be?",
        "Do you think you'll marry your current girlfriend/boyfriend?",
        "What is the most illegal thing you have ever done?",
        "Would you choose to save 100 people without anyone knowing about it or not save them but have everyone praise you for it?",
        "Who in this room would be the worst person to date? Why?",
        "If someone offered you $1 million to break up with your girlfriend/boyfriend, would you do it?",
        "If you could go back in time in erase one thing you said or did, what would it be?",
        "Have you ever thought about cheating on your partner?",
        "If you could suddenly become invisible, what would you do?",
        "Have you ever waved at someone thinking they saw you when really they didn't? What did you do when you realized it?",
        "What's the longest time you've stayed in the bathroom, and why did you stay for that long?",
        "Describe the strangest dream you've ever had. Did you like it?",
        "What is your biggest fear?",
        "Do you pee in the shower?",
        "What is the most childish thing that you still do?",
        "How far would you go to land the guy or girl of your dreams?",
        "Who is one person you pretend to like, but actually didn't?",
        "When was the last time you wet the bed?",
        "Have you ever pretended to be sick to get out of something? If so, what was it?",
        "What is something you’ve done to try to be ‘cooler’?",
        "What is something that no one else knows about you?",
        "What is the worst date you’ve ever been on?",
        "Have you ever been stood up on a date?",
        "Who are you jealous of?",
        "Who do you hate the most?",
        "Would you rather be a guy than a girl? Why?",
        "How long have you gone without a shower?",
        "What's one thing you would never eat on a first date?",
        "What have you seen that you wish you could unsee?",
        "If you switched genders for the day, what would you do?",
        "If your car broke down in the middle of the road, who in this game would be the last person you would call? Why?",
        "What's the most useless piece of knowledge you know?",
        "What did you learn in school that you wish you could forget?",
        "If you could only use one swear word for the rest of your life, which one would you choose?",
        "If you knew your friend's partner was cheating on her, what would you do?",
        "Name one thing you would change about each person in this game.",
        "What's your biggest turn-on?",
        "Have you ever sent out a nude",
        "Have you ever received a nude selfie? Who was it from?",
        "What is your worst habit?",
        "If you had to choose between dating someone ugly who was good in bed or dating someone hot who was bad in bed, which would you choose?",
        "When was the last time you flexed in the mirror?",
        "Would you take steroids?",
        "Who do you think is the hottest in group?",
        "What is your biggest turn-off?",
        "If you had to choose between being poor and smart or being rich and dumb, what would you choose?",
        "What have you lied to your partner about?",
        "Have you ever cheated on your partner?",
        "Would you go out with an older woman?",
        "When was the last time you cried?",
        "Have you ever lied about your age?",
        "What would you do if you found out your partner liked someone else?",
        "What is your greatest fear in a relationship?",
        "What is one disturbing fact that we should know about you?",
        "Who's the most annoying person in this room?",
        "Have you ever flashed someone?",
        "Have you ever sexted anyone?"
    ]
    const randTotuus = tasks[Math.floor(Math.random() * tasks.length)]

    return randTotuus;
}